services:
  db:
    container_name: shoplite_db_staging
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-shoplite_staging}
    volumes:
      - shoplite_pgdata_staging:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  api:
    container_name: shoplite_api_staging
    environment:
      APP_VERSION: ${APP_VERSION:-staging}
      LOG_LEVEL: debug
      NODE_ENV: staging

  frontend:
    container_name: shoplite_frontend_staging

  proxy:
    container_name: shoplite_proxy_staging
    ports:
      - "8081:80"

volumes:
  shoplite_pgdata_staging:
